### ISSUE TITLE
Confirmation email not including flight or price data

### ISSUE THREAD

**Issue by b8ne** [SENG3160-2018/flightpub#8]
**Describe the bug**
Confirmation email is sent and recieved however the email does not contain any flight purchase data.

**To Reproduce**
1. Select Business user.
2. Complete form with 'Atlanta' to 'JFK', 'Business Class', 'Premium Tickets', '12/10/2018'.
3. Add flight to cart.
4. Complete payment.
5. Fill in name and email and submit form.
6. View received email in email client of choice.
7. See flight and price details are incorrect.

**Expected behavior**
Confirmation email should match flights purchased, including multi leg flights.

**Screenshots**
![screen shot 2018-10-12 at 1 31 19 pm](https://user-images.githubusercontent.com/19263633/46844568-66e10400-ce23-11e8-8497-6c9305b35844.png)

**Additional context**
As this has passed previously, it's assumed that the bug lies around the case of multiple flights purchased, or if a single flight ticket contains multiple legs.

**Comment by ebbanat** [comment]
The issue was that the cart (containing the flights) was being cleared before the email was generated.

I also commented out the code where prices are retrieved for the flights as it wouldn't allow me to test this area.

![screenshot from 2018-10-18 09-53-06](https://user-images.githubusercontent.com/16621776/47122749-e8bdab00-d2c3-11e8-96ef-3590f9ec43fd.png)

Email displaying that receipts are being generated with the cart.
